### PR TITLE
feat: add MinCommissionRate param

### LINKED ISSUE #109: Validator Min. Commission 5%
**Problem definition**
With the passing of proposal 11322 the community expressed the wish to implement a minimum commission of 5% for validators on the network. This highly relates to #89.

Update:  Given that this is feature in Cosmos SDK 0.46, a temporary solution that allows for a minimum 5% commission to be enforced for all validators should be sufficient.

### PR DESCRIPTION
**Pull request by alchemist-ti**
## Description

Resolves: https://github.com/classic-terra/core/issues/109, Add `MinCommissionRate` param to `x/staking` module. Cherry-pick from https://github.com/cosmos/cosmos-sdk/pull/10529, https://github.com/cosmos/cosmos-sdk/pull/12028.

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] added `!` to the type prefix if API or client breaking change
* [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] provided a link to the relevant issue or specification
* [ ] followed the guidelines for [building modules](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules)
* [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
* [ ] added a changelog entry to `CHANGELOG.md`
* [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] updated the relevant documentation or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] confirmed all author checklist items have been addressed 
* [ ] reviewed state machine logic
* [ ] reviewed API design and naming
* [ ] reviewed documentation is accurate
* [ ] reviewed tests and test coverage
* [ ] manually tested (if applicable)

### CODE REVIEW

**Review by nghuyenthevinh2000 — APPROVED** [review]
@alchemist-ti can you clean up this pr again then merge. LGTM!

Please create a new release for this also, then update go.mod on core to use new sdk

**Comment by alchemist-ti** [comment]
> @alchemist-ti can you clean up this pr again then merge. LGTM!
> 
> Please create a new release for this also, then update go.mod on core to use new sdk

@nghuyenthevinh2000 Ok, v0.45.14?

**Comment by nghuyenthevinh2000** [comment]
Something with -terra name

**Comment by alchemist-ti** [comment]
> Something with -terra name

Following the previous rules, I released [v0.45.14-classic](https://github.com/classic-terra/cosmos-sdk/releases/tag/v0.45.14-classic)

**Pull request merged**
